---

- hosts: all
  vars:
    postgresql_version: 9.3
    postgresql_cluster_name: "data01"
    postgresql_data_directory: /data/postgresql/
    postgresql_conf_directory: /data/postgresql/
    postgresql_shared_buffers: 348MB
    
  roles:
    - PostgreSQL
