---

- hosts: all
  vars:
    onmetal_disk_mirror_or_stripe: stripe
    onmetal_db_user: postgres
    onmetal_db_group: postgres
    postgresql_version: 9.3
    postgresql_cluster_name: "data01"
    postgresql_data_directory: /data/postgresql/
    postgresql_conf_directory: /data/postgresql/
  roles:
    - ansible-roles_onmetal-db
    - PostgreSQL
